import Mathlib

namespace RouteBB45Fourier

/- The coefficient-level Fourier atom used by the Route-B probe.  `eps` is a
   fourth-root phase and `z` is the formal Laurent atom for one joint.  The
   theorem below is intentionally algebraic: the analytic identification
   `z = exp (I*q)` is a separate source/analysis obligation. -/
def fourierCos (eps z : ℂ) : ℂ := (eps * z + conj eps * z⁻¹) / 2

def fourierSin (eps z : ℂ) : ℂ :=
  ((-Complex.I) * eps * z + Complex.I * conj eps * z⁻¹) / 2

def dhStep (ct st ca sa a d : ℂ) (i j : Fin 4) : ℂ :=
  match i.1, j.1 with
  | 0, 0 => ct
  | 0, 1 => -st * ca
  | 0, 2 => st * sa
  | 0, 3 => ct * a
  | 1, 0 => st
  | 1, 1 => ct * ca
  | 1, 2 => -ct * sa
  | 1, 3 => st * a
  | 2, 0 => 0
  | 2, 1 => sa
  | 2, 2 => ca
  | 2, 3 => d
  | 3, 0 => 0
  | 3, 1 => 0
  | 3, 2 => 0
  | 3, 3 => 1
  | _, _ => 0

def fourierDHStep (eps z ca sa a d : ℂ) (i j : Fin 4) : ℂ :=
  dhStep (fourierCos eps z) (fourierSin eps z) ca sa a d i j

/- Reusable single-step normal form: every entry is a fixed Laurent expression
   in z and z⁻¹, with coefficients generated by eps, ca, sa, a, d. -/
theorem fourierDHStep_normal_form (eps z ca sa a d : ℂ) :
    (fourierDHStep eps z ca sa a d 0 0 = fourierCos eps z) ∧
    (fourierDHStep eps z ca sa a d 0 1 = -fourierSin eps z * ca) ∧
    (fourierDHStep eps z ca sa a d 0 2 = fourierSin eps z * sa) ∧
    (fourierDHStep eps z ca sa a d 0 3 = fourierCos eps z * a) ∧
    (fourierDHStep eps z ca sa a d 1 0 = fourierSin eps z) ∧
    (fourierDHStep eps z ca sa a d 1 1 = fourierCos eps z * ca) ∧
    (fourierDHStep eps z ca sa a d 1 2 = -fourierCos eps z * sa) ∧
    (fourierDHStep eps z ca sa a d 1 3 = fourierSin eps z * a) ∧
    (fourierDHStep eps z ca sa a d 2 1 = sa) ∧
    (fourierDHStep eps z ca sa a d 2 2 = ca) ∧
    (fourierDHStep eps z ca sa a d 2 3 = d) ∧
    (fourierDHStep eps z ca sa a d 3 3 = 1) := by
  simp [fourierDHStep, dhStep]

/- The exact phase constants used by the six Route-B steps. -/
def routeBOffsetPhase : Fin 6 → ℂ
  | 0 => 1
  | 1 => -Complex.I
  | 2 => Complex.I
  | 3 => 1
  | 4 => 1
  | 5 => 1

def routeBCosAlpha : Fin 6 → ℂ
  | 0 => 0
  | 1 => 1
  | 2 => 0
  | 3 => 0
  | 4 => 0
  | 5 => 1

def routeBSinAlpha : Fin 6 → ℂ
  | 0 => -1
  | 1 => 0
  | 2 => 1
  | 3 => -1
  | 4 => 1
  | 5 => 0

def routeBA : Fin 6 → ℂ
  | 0 => 2 / 25
  | 1 => 21 / 100
  | _ => 0

def routeBD : Fin 6 → ℂ
  | 0 => 1 / 10
  | 1 => 0
  | 2 => 1 / 20
  | 3 => 19 / 100
  | 4 => 0
  | 5 => 7 / 100

theorem routeB_exact_single_step_parameters :
    routeBOffsetPhase 0 = 1 ∧ routeBOffsetPhase 1 = -Complex.I ∧
    routeBOffsetPhase 2 = Complex.I ∧ routeBOffsetPhase 3 = 1 ∧
    routeBOffsetPhase 4 = 1 ∧ routeBOffsetPhase 5 = 1 ∧
    routeBCosAlpha 0 = 0 ∧ routeBCosAlpha 1 = 1 ∧
    routeBCosAlpha 2 = 0 ∧ routeBCosAlpha 3 = 0 ∧
    routeBCosAlpha 4 = 0 ∧ routeBCosAlpha 5 = 1 ∧
    routeBSinAlpha 0 = -1 ∧ routeBSinAlpha 1 = 0 ∧
    routeBSinAlpha 2 = 1 ∧ routeBSinAlpha 3 = -1 ∧
    routeBSinAlpha 4 = 1 ∧ routeBSinAlpha 5 = 0 ∧
    routeBA 0 = 2 / 25 ∧ routeBA 1 = 21 / 100 ∧
    routeBA 2 = 0 ∧ routeBA 3 = 0 ∧ routeBA 4 = 0 ∧ routeBA 5 = 0 ∧
    routeBD 0 = 1 / 10 ∧ routeBD 1 = 0 ∧ routeBD 2 = 1 / 20 ∧
    routeBD 3 = 19 / 100 ∧ routeBD 4 = 0 ∧ routeBD 5 = 7 / 100 := by
  norm_num [routeBOffsetPhase, routeBCosAlpha, routeBSinAlpha, routeBA,
    routeBD]

#print axioms fourierDHStep_normal_form
#print axioms routeB_exact_single_step_parameters

end RouteBB45Fourier
