import Mathlib

namespace RouteBP5MovingChartLieDefect

/-- Symmetric 2x2 quadratic form for `[[a,b],[b,c]]`. -/
def qform2 (a b c x y : ℝ) : ℝ :=
  a * x ^ 2 + 2 * b * x * y + c * y ^ 2

/-- Bilinear form associated with the same symmetric 2x2 matrix. -/
def bilinear2 (a b c u1 u2 v1 v2 : ℝ) : ℝ :=
  a * u1 * v1 + b * u1 * v2 + b * u2 * v1 + c * u2 * v2

/-- First component of a 2x2 linear action. -/
def lin1 (m11 m12 x y : ℝ) : ℝ := m11 * x + m12 * y

/-- Second component of a 2x2 linear action. -/
def lin2 (m21 m22 x y : ℝ) : ℝ := m21 * x + m22 * y

/-- Quadratic packet for the pulled-back metric `M = Jᵀ W J`. -/
def pullbackQ2
    (wa wb wc j11 j12 j21 j22 x y : ℝ) : ℝ :=
  qform2 wa wb wc
    (lin1 j11 j12 x y) (lin2 j21 j22 x y)

/-- Bilinear packet for the same pulled-back metric. -/
def pullbackBilinear2
    (wa wb wc j11 j12 j21 j22 u1 u2 v1 v2 : ℝ) : ℝ :=
  bilinear2 wa wb wc
    (lin1 j11 j12 u1 u2) (lin2 j21 j22 u1 u2)
    (lin1 j11 j12 v1 v2) (lin2 j21 j22 v1 v2)

/-- Symmetric Jacobian packet `v ↦ <Bv,v>_W + <v,Bv>_W`. -/
def symJacobianQ2
    (wa wb wc b11 b12 b21 b22 x y : ℝ) : ℝ :=
  bilinear2 wa wb wc
      (lin1 b11 b12 x y) (lin2 b21 b22 x y) x y
    + bilinear2 wa wb wc
      x y (lin1 b11 b12 x y) (lin2 b21 b22 x y)

/-- Physical base-flow Lie-defect packet
`D_x W[b] + (D_x b)ᵀ W + W D_x b`. -/
def baseLieDefectQ2
    (wa wb wc dwa dwb dwc b11 b12 b21 b22 x y : ℝ) : ℝ :=
  qform2 dwa dwb dwc x y
    + symJacobianQ2 wa wb wc b11 b12 b21 b22 x y

/-- Directional derivative of the pulled-back metric along the normalized
perturbation. `Kη` represents `(D_z J[c])η`, while `dW` already denotes the
physical directional packet `D_x W[b]` after the vector covariance `Jc=b`. -/
def pullbackDirectionalMetricQ2
    (wa wb wc dwa dwb dwc
      j11 j12 j21 j22 k11 k12 k21 k22 x y : ℝ) : ℝ :=
  bilinear2 wa wb wc
      (lin1 k11 k12 x y) (lin2 k21 k22 x y)
      (lin1 j11 j12 x y) (lin2 j21 j22 x y)
    + qform2 dwa dwb dwc
      (lin1 j11 j12 x y) (lin2 j21 j22 x y)
    + bilinear2 wa wb wc
      (lin1 j11 j12 x y) (lin2 j21 j22 x y)
      (lin1 k11 k12 x y) (lin2 k21 k22 x y)

/-- Symmetric normalized Jacobian packet generated by `C = D_z c` in the
pulled-back metric. -/
def normalizedSymQ2
    (wa wb wc j11 j12 j21 j22 c11 c12 c21 c22 x y : ℝ) : ℝ :=
  pullbackBilinear2 wa wb wc j11 j12 j21 j22
      (lin1 c11 c12 x y) (lin2 c21 c22 x y) x y
    + pullbackBilinear2 wa wb wc j11 j12 j21 j22
      x y (lin1 c11 c12 x y) (lin2 c21 c22 x y)

/-- Expanded normalized Lie-defect packet
`D_z M[c] + Cᵀ M + M C`. -/
def normalizedBaseLieDefectExpandedQ2
    (wa wb wc dwa dwb dwc
      j11 j12 j21 j22 k11 k12 k21 k22
      c11 c12 c21 c22 x y : ℝ) : ℝ :=
  pullbackDirectionalMetricQ2
      wa wb wc dwa dwb dwc
      j11 j12 j21 j22 k11 k12 k21 k22 x y
    + normalizedSymQ2
      wa wb wc j11 j12 j21 j22 c11 c12 c21 c22 x y

/-- First component of the exact connection-cancellation combination
`(D_z J[c])η + J(D_z c η)`. -/
def combinedAction1
    (j11 j12 k11 k12 c11 c12 c21 c22 x y : ℝ) : ℝ :=
  lin1 k11 k12 x y
    + lin1 j11 j12
      (lin1 c11 c12 x y) (lin2 c21 c22 x y)

/-- Second component of the same exact connection-cancellation combination. -/
def combinedAction2
    (j21 j22 k21 k22 c11 c12 c21 c22 x y : ℝ) : ℝ :=
  lin2 k21 k22 x y
    + lin2 j21 j22
      (lin1 c11 c12 x y) (lin2 c21 c22 x y)

/-- Combined form of the normalized Lie defect after grouping the connection
term and normalized perturbation Jacobian before applying covariance. -/
def normalizedBaseLieDefectCombinedQ2
    (wa wb wc dwa dwb dwc
      j11 j12 j21 j22 k11 k12 k21 k22
      c11 c12 c21 c22 x y : ℝ) : ℝ :=
  qform2 dwa dwb dwc
      (lin1 j11 j12 x y) (lin2 j21 j22 x y)
    + bilinear2 wa wb wc
      (combinedAction1 j11 j12 k11 k12 c11 c12 c21 c22 x y)
      (combinedAction2 j21 j22 k21 k22 c11 c12 c21 c22 x y)
      (lin1 j11 j12 x y) (lin2 j21 j22 x y)
    + bilinear2 wa wb wc
      (lin1 j11 j12 x y) (lin2 j21 j22 x y)
      (combinedAction1 j11 j12 k11 k12 c11 c12 c21 c22 x y)
      (combinedAction2 j21 j22 k21 k22 c11 c12 c21 c22 x y)

/-- Pure product-rule regrouping: the expanded normalized packet equals the
combined connection packet before any source or covariance assumption. -/
theorem normalized_lie_defect_expanded_eq_combined
    (wa wb wc dwa dwb dwc
      j11 j12 j21 j22 k11 k12 k21 k22
      c11 c12 c21 c22 x y : ℝ) :
    normalizedBaseLieDefectExpandedQ2
        wa wb wc dwa dwb dwc
        j11 j12 j21 j22 k11 k12 k21 k22
        c11 c12 c21 c22 x y
      = normalizedBaseLieDefectCombinedQ2
        wa wb wc dwa dwb dwc
        j11 j12 j21 j22 k11 k12 k21 k22
        c11 c12 c21 c22 x y := by
  simp only [normalizedBaseLieDefectExpandedQ2,
    pullbackDirectionalMetricQ2, normalizedSymQ2, pullbackBilinear2,
    normalizedBaseLieDefectCombinedQ2, combinedAction1, combinedAction2,
    qform2, bilinear2, lin1, lin2]
  ring

/-- Minimal typed seam for differentiating `Jc=b`: a source-side chain-rule
identity plus symmetry of the chart Hessian converts `D_z(Jc)[η]` into the
consumer form `(D_z J[c])η + J(D_zc η)`. -/
theorem differentiated_vector_covariance_seam
    (dJetaC1 dJetaC2 dJcEta1 dJcEta2 jC1 jC2 bJ1 bJ2 : ℝ)
    (hchain1 : dJetaC1 + jC1 = bJ1)
    (hchain2 : dJetaC2 + jC2 = bJ2)
    (hhess1 : dJetaC1 = dJcEta1)
    (hhess2 : dJetaC2 = dJcEta2) :
    dJcEta1 + jC1 = bJ1 ∧ dJcEta2 + jC2 = bJ2 := by
  constructor
  · linarith
  · linarith

/-- Main T-P5-095 algebraic kernel.  If the differentiated vector covariance
`(D_zJ[c])η + J(Cη) = B(Jη)` holds componentwise, then the complete normalized
base-flow Lie defect is exactly the physical Lie defect evaluated at `Jη`.
No inverse, square root, Hessian penalty, or chart condition number appears. -/
theorem moving_chart_base_lie_defect_quadratic_congruence
    (wa wb wc dwa dwb dwc
      j11 j12 j21 j22 k11 k12 k21 k22
      c11 c12 c21 c22 b11 b12 b21 b22 x y : ℝ)
    (hcov1 :
      combinedAction1 j11 j12 k11 k12 c11 c12 c21 c22 x y
        = lin1 b11 b12
          (lin1 j11 j12 x y) (lin2 j21 j22 x y))
    (hcov2 :
      combinedAction2 j21 j22 k21 k22 c11 c12 c21 c22 x y
        = lin2 b21 b22
          (lin1 j11 j12 x y) (lin2 j21 j22 x y)) :
    normalizedBaseLieDefectExpandedQ2
        wa wb wc dwa dwb dwc
        j11 j12 j21 j22 k11 k12 k21 k22
        c11 c12 c21 c22 x y
      = baseLieDefectQ2
        wa wb wc dwa dwb dwc b11 b12 b21 b22
        (lin1 j11 j12 x y) (lin2 j21 j22 x y) := by
  rw [normalized_lie_defect_expanded_eq_combined]
  simp only [normalizedBaseLieDefectCombinedQ2, baseLieDefectQ2,
    symJacobianQ2]
  rw [hcov1, hcov2]

/-- Any physical same-metric signed relative bound transports to the pulled
metric with exactly the same scalar `rho`; this is just quadratic substitution
and does not require `J` to be inverted. -/
theorem base_lie_defect_rate_pullback
    (wa wb wc dwa dwb dwc b11 b12 b21 b22
      j11 j12 j21 j22 rho x y : ℝ)
    (hphys : ∀ u v : ℝ,
      baseLieDefectQ2 wa wb wc dwa dwb dwc b11 b12 b21 b22 u v
        ≤ 2 * rho * qform2 wa wb wc u v) :
    baseLieDefectQ2 wa wb wc dwa dwb dwc b11 b12 b21 b22
        (lin1 j11 j12 x y) (lin2 j21 j22 x y)
      ≤ 2 * rho * pullbackQ2 wa wb wc j11 j12 j21 j22 x y := by
  simpa [pullbackQ2] using
    hphys (lin1 j11 j12 x y) (lin2 j21 j22 x y)

/-- Consumer-facing version: once the exact congruence has been checked, the
same signed relative rate certificate is sufficient in normalized coordinates. -/
theorem normalized_lie_defect_rate_of_congruence
    (wa wb wc dwa dwb dwc b11 b12 b21 b22
      j11 j12 j21 j22 rho x y sc : ℝ)
    (hcong : sc = baseLieDefectQ2 wa wb wc dwa dwb dwc b11 b12 b21 b22
      (lin1 j11 j12 x y) (lin2 j21 j22 x y))
    (hphys : ∀ u v : ℝ,
      baseLieDefectQ2 wa wb wc dwa dwb dwc b11 b12 b21 b22 u v
        ≤ 2 * rho * qform2 wa wb wc u v) :
    sc ≤ 2 * rho * pullbackQ2 wa wb wc j11 j12 j21 j22 x y := by
  rw [hcong]
  exact base_lie_defect_rate_pullback
    wa wb wc dwa dwb dwc b11 b12 b21 b22
    j11 j12 j21 j22 rho x y hphys

/-- A componentwise-composition shortcut is not vector covariance: even in one
dimension, composing the perturbation component without the chart Jacobian can
fail `Jc=b`. -/
theorem componentwise_composition_shortcut_counterexample :
    (2 : ℝ) * 1 ≠ 1 := by
  norm_num

#print axioms normalized_lie_defect_expanded_eq_combined
#print axioms differentiated_vector_covariance_seam
#print axioms moving_chart_base_lie_defect_quadratic_congruence
#print axioms base_lie_defect_rate_pullback
#print axioms normalized_lie_defect_rate_of_congruence
#print axioms componentwise_composition_shortcut_counterexample

end RouteBP5MovingChartLieDefect
